version: "3.8"
services:
  mongodb:
    image: mongo
    ports:
      - "27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=password
    healthcheck:
      test: ["CMD", "mongosh", "--username=root", "--password=password"]
      interval: 5s
      timeout: 3s
      start_period: 15s
      retries: 30
  react:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./frontend/src
        target: /app/src
      - type: bind
        source: ./frontend/public
        target: /app/public
    ports:
      - "3000:3000"
    depends_on:
      - express
  express:
    build:
      context: ./backend
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./backend
        target: /app
    ports:
      - "5000:5000"
    depends_on:
      mongodb:
        condition: service_healthy
